#!/bin/bash

GOOGLE_SHEET_ID="YOUR_SHEET_ID"

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

google-docs-i18n-strings -p "ios, iosUtil" -s $GOOGLE_SHEET_ID -i "$DIR/SupportingFiles" -u "$DIR/Code"